CREATE DATABASE CONSULTA
USE CONSULTA
GO

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY NOT NULL,
IDMASCOTA INT,
EDAD_C INT,
RUT VARCHAR (13),
NOMBRE VARCHAR (40),
PAGO VARCHAR (10),
DATOS_CLIENTE VARCHAR (100)
);


CREATE TABLE MASCOTA(
IDMASCOTA INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (40),
EDAD INT,
RAZA VARCHAR (50),
ESTERILIZADO VARCHAR (10),
SEXO VARCHAR (10),
TIPO_ATENCION VARCHAR (10),
FECHA_NACIMIENTO DATE,
LISTADO_MASCOTAS VARCHAR (100)
);

ALTER TABLE CLIENTE ADD FOREIGN KEY (IDMASCOTA) REFERENCES MASCOTA (IDMASCOTA)

--- para insertar datos se utiliza la siguiente sentencia 

INSERT INTO MASCOTA VALUES (1,'FOCA',31,'QUILTRO','SI','MACHO','CONTROL', '1989/01/01','SIN INFORMACION')
INSERT INTO CLIENTE VALUES (1, 1,31,'11.111.111-1','VICKY ROSAS','EFECTIVO','DUEÑA DEL PERRO COGOTE DE FOCA')

SELECT * FROM MASCOTA
SELECT * FROM CLIENTE

drop table CLIENTE;
drop table MASCOTA;