//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int IDCLIENTE { get; set; }
        public Nullable<int> IDMASCOTA { get; set; }
        public Nullable<int> EDAD_C { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string PAGO { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
    }
}
