//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASCOTA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int IDMASCOTA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string RAZA { get; set; }
        public string ESTERILIZADO { get; set; }
        public string SEXO { get; set; }
        public string TIPO_ATENCION { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
